version: '3.5'

services:

  alpha:
    image: mysql
    container_name: alpha
    hostname: alpha
    ports:
      - '39393:3306'
    restart: unless-stopped
    # sets the network address which the member provides for connections from other members, specified as a host:port formatted string.
    command:
      [
        "mysqld",
        "--loose-group-replication-local-address=alpha:6606"
      ]
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: hoge
      MYSQL_DATABASE: lpg
    volumes:
      - ./configs/my-cnf:/etc/mysql/my.cnf
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      interval: 2s
      retries: 20

  beta:
    image: mysql
    container_name: beta
    hostname: beta
    ports:
      - '39394:3306'
    restart: unless-stopped
    # sets the network address which the member provides for connections from other members, specified as a host:port formatted string.
    command:
      [
        "mysqld",
        "--loose-group-replication-local-address=beta:6606"
      ]
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: hoge
      MYSQL_DATABASE: lpg
    volumes:
      - ./configs/my-cnf:/etc/mysql/my.cnf
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      interval: 2s
      retries: 20

  gamma:
    image: mysql
    container_name: gamma
    hostname: gamma
    ports:
      - '39395:3306'
    restart: unless-stopped
    # sets the network address which the member provides for connections from other members, specified as a host:port formatted string.
    command:
      [
        "mysqld",
        "--loose-group-replication-local-address=gamma:6606"
      ]
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: hoge
      MYSQL_DATABASE: lpg
    volumes:
      - ./configs/my-cnf:/etc/mysql/my.cnf
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      interval: 2s
      retries: 20
